### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by NotDSF** [pozm/Synapse#1]
I need support mentally, do you offer that service? All help will be admired.

**Comment by fatesc** [comment]
> I need support mentally, do you offer that service? All help will be admired.

cry about it 😂

**Comment by NotDSF** [comment]
> 
> 
> > I need support mentally, do you offer that service? All help will be admired.
> 
> cry about it 😂

Jumping off the nearest bridge within a 50 mile radius :(

**Comment by NotDSF** [comment]
asdasdsad

**Comment by NotDSF** [comment]
get emailed
