### ISSUE TITLE
there's no syn function

### ISSUE THREAD

**Issue by stan2474** [pozm/Synapse#2]
the title answers it all

**Comment by NotDSF** [comment]
stfu skid

**Comment by stan2474** [comment]
> stfu skid

you skid more then me stfu

**Comment by NotDSF** [comment]
mad? skid

**Comment by NotDSF** [comment]
mr random string.lua

**Comment by NotDSF** [comment]
proof you skid bro 
![image](https://user-images.githubusercontent.com/67711164/109661004-6d41b900-7b61-11eb-854d-d2bbd37bc941.png)

**Comment by NotDSF** [comment]
kjskfsdhfjsdgfhjagdty2q34r56sabdcasgdsafgdsagdasdsad
